### ISSUE TITLE
using the snippetfield plugin in a theme

### ISSUE THREAD

**Issue by louis-ev** [samnabi/shopkit#127]
Hi,

I've been trying to set-up [snippetfield](https://github.com/jenstornell/kirby-snippetfield) in a blueprint (and snippet) without touching the shopkit plugin. 

However since `snippetfield.path` is set in `shopkit/registry/snippets.php` I haven't found a way to link the field to a snippet, for examples:

```
  slide:
    label: Slide
    type: snippetfield
    modal: medium
    style: items
    snippet: collection/snippet
    fields:
      image:
        label: Image
        type: select
        options: images
```

The path seems to look for collection/snippet using the `snippetfield.path`, which redirects to a shopkit folder. Is that right? Any other way to do it?
